AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Post Cost Explorer report to Slack
Parameters:
  SlackWebhookUrl:
    Type: String
  ScheduleExpression:
    Type: String
    Default: "cron(0 0 * * ? *)"
Resources:
  postCostExplorerReportToSlack:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./src
      Role: !GetAtt CostExplorerReportLambdaIAMRole.Arn
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
  CostExplorerReportLambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies: 
        - 
          PolicyName: "root"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              -  #Policy to allow CostExplorerAPI
                Effect: "Allow"
                Action:
                  - ce:*
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: 
              - "sts:AssumeRole"
            Principal:
              Service: 
                - "lambda.amazonaws.com"